export const PermissionCode = {
  // User Management
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_USER: "VIEW_USER",
  MANAGE_USER_STATUS: "MANAGE_USER_STATUS",

  // Product Management
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  VIEW_PRODUCT: "VIEW_PRODUCT",
  APPROVE_PRODUCT: "APPROVE_PRODUCT",

  // Order Management
  CREATE_ORDER: "CREATE_ORDER",
  UPDATE_ORDER: "UPDATE_ORDER",
  VIEW_ORDER: "VIEW_ORDER",
  CANCEL_ORDER: "CANCEL_ORDER",
  MANAGE_ORDERS: "MANAGE_ORDERS",

  // Shop Management
  CREATE_SHOP: "CREATE_SHOP",
  UPDATE_SHOP: "UPDATE_SHOP",
  DELETE_SHOP: "DELETE_SHOP",
  VIEW_SHOP: "VIEW_SHOP",
  MANAGE_SHOP_STATUS: "MANAGE_SHOP_STATUS",

  // Category & Brand
  CREATE_CATEGORY: "CREATE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  CREATE_BRAND: "CREATE_BRAND",
  UPDATE_BRAND: "UPDATE_BRAND",
  DELETE_BRAND: "DELETE_BRAND",

  // Review & Rating
  CREATE_REVIEW: "CREATE_REVIEW",
  UPDATE_REVIEW: "UPDATE_REVIEW",
  DELETE_REVIEW: "DELETE_REVIEW",
  MODERATE_REVIEW: "MODERATE_REVIEW",

  // Voucher & Promotion
  CREATE_VOUCHER: "CREATE_VOUCHER",
  UPDATE_VOUCHER: "UPDATE_VOUCHER",
  DELETE_VOUCHER: "DELETE_VOUCHER",
  MANAGE_PLATFORM_VOUCHER: "MANAGE_PLATFORM_VOUCHER",

  // Admin & System
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",
  VIEW_AUDIT_LOG: "VIEW_AUDIT_LOG",
  MANAGE_SYSTEM_SETTINGS: "MANAGE_SYSTEM_SETTINGS",

  // Address Management
  CREATE_ADDRESS: "CREATE_ADDRESS",
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  DELETE_ADDRESS: "DELETE_ADDRESS",

  // Reports
  VIEW_SHOP_REPORTS: "VIEW_SHOP_REPORTS",
  VIEW_SYSTEM_REPORTS: "VIEW_SYSTEM_REPORTS",

  // Disputes
  MANAGE_DISPUTES: "MANAGE_DISPUTES",
} as const;

export type PermissionCode =
  (typeof PermissionCode)[keyof typeof PermissionCode];
